name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4  # Ensures the repository is available

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable  # Ensures Rust toolchain is installed

    - name: Run build
      run: cargo build --verbose  # Compiles the Rust project

    - name: Run tests
      run: cargo test --verbose  # Runs the test suite
